<?php

namespace App\Mail;

use Illuminate\Bus\Queueable;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Carbon;

/**
 * Phase 3 — §3.3: the monthly-report email. Carries the booklet PDF (generated by
 * ReportsController::gatherBooklet, the SAME code path as the downloadable monthlyPdf endpoint)
 * as an in-memory attachment. One Mailable per recipient (delivery-failure isolation + privacy).
 */
class MonthlyReportMail extends Mailable
{
    use Queueable, SerializesModels;

    public function __construct(
        public int $year,
        public int $month,
        public string $pdfContent
    ) {}

    public function build(): self
    {
        $name = Carbon::createFromDate($this->year, $this->month, 1)->format('F Y');

        return $this->subject("DMC Internal Medicine — Monthly Report {$name}")
            ->view('mail.monthly-report')
            ->with(['year' => $this->year, 'month' => $this->month, 'name' => $name])
            ->attachData($this->pdfContent, sprintf('dmc-monthly-%d-%02d.pdf', $this->year, $this->month),
                ['mime' => 'application/pdf']);
    }
}
