<?php

namespace Tests\Feature;

use App\Models\Admission;
use App\Models\AuditLog;
use App\Models\Patient;
use App\Models\User;
use App\Support\Totp;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Storage;
use PHPUnit\Framework\Attributes\Group;
use Tests\TestCase;

/**
 * PERF-07 — the queued monthly-booklet PDF lives on the container's LOCAL disk
 * (GenerateMonthlyPdf.php, storage/app/reports), which Coolify recreates empty on every deploy
 * (CLAUDE.md §10: "no staging / every deploy is a production change"). Before this fix, a
 * notification's download link issued before a deploy 404'd forever with no recovery path other
 * than asking the admin to re-run the whole report. downloadGenerated() now regenerates the exact
 * same booklet from the same inputs (the key IS the inputs: monthly-{year}-{userId}.pdf) and
 * stores it back before serving, so the link heals itself instead of dying. This deliberately does
 * NOT move PDFs to object storage — see the task scope — it only closes the "file already gone"
 * gap on the existing local-disk design.
 */
#[Group('pdf')]
class ReportPdfSelfHealingTest extends TestCase
{
    use RefreshDatabase;

    private function admin(): User
    {
        return User::create(['username' => 'sh_admin_'.substr(md5(uniqid('', true)), 0, 6),
            'name' => 'SH Admin', 'password' => 'secret12345', 'role' => User::ROLE_ADMIN, 'active' => 1,
            'mfa_secret' => Totp::secret(), 'mfa_enrolled_at' => now()]);
    }

    private function seedFixture(): void
    {
        $p = Patient::create(['mrn' => '93000001', 'name' => 'SH Patient']);
        Admission::create(['patient_id' => $p->id, 'admit_date' => '2024-06-02', 'discharge_date' => '2024-06-07',
            'outcome' => 'Alive', 'transfer_type' => 'discharge from ward', 'discharge_to' => 'Home',
            'current_location' => 'Ward', 'is_longterm' => 0, 'is_new_assignment' => 0]);
    }

    public function test_download_regenerates_and_serves_a_real_pdf_when_the_stored_file_is_missing(): void
    {
        Storage::fake('local');
        $this->seedFixture();
        $admin = $this->admin();
        $key = "monthly-2024-{$admin->id}.pdf";

        // simulate the post-deploy state: the notification/link exists, but the container that
        // generated it (and its local disk) is gone — nothing was ever written for this key.
        Storage::disk('local')->assertMissing("reports/{$key}");

        $res = $this->actingAs($admin)->get("/reports/pdf-download/{$key}");

        $res->assertOk();
        $res->assertDownload("CONFIDENTIAL-{$key}");
        // response()->download() streams a BinaryFileResponse, whose getContent() is not the file
        // body (it's false/empty by design) — read the regenerated bytes back off disk instead.
        $this->assertStringStartsWith('%PDF', Storage::disk('local')->get("reports/{$key}"));
    }

    /**
     * response()->download(...)->deleteFileAfterSend() schedules its cleanup via PHP's
     * register_shutdown_function, which does not fire mid-test (only at PHPUnit process exit), so
     * the freshly-regenerated file is still observable on disk right after the request — this is
     * exactly what proves the controller stored it back rather than only streaming it once.
     */
    public function test_regenerated_file_is_stored_back_so_it_is_not_rebuilt_on_every_request(): void
    {
        Storage::fake('local');
        $this->seedFixture();
        $admin = $this->admin();
        $key = "monthly-2024-{$admin->id}.pdf";

        $this->actingAs($admin)->get("/reports/pdf-download/{$key}")->assertOk();

        Storage::disk('local')->assertExists("reports/{$key}");
        $this->assertStringStartsWith('%PDF', Storage::disk('local')->get("reports/{$key}"));
    }

    public function test_download_writes_the_normal_audit_row_on_the_regenerated_path_too(): void
    {
        Storage::fake('local');
        $this->seedFixture();
        $admin = $this->admin();
        $key = "monthly-2024-{$admin->id}.pdf";

        $this->actingAs($admin)->get("/reports/pdf-download/{$key}")->assertOk();

        $this->assertSame(1, AuditLog::where('action', 'report.pdf.download')->count());
        $row = AuditLog::where('action', 'report.pdf.download')->first();
        $this->assertSame($key, $row->details['key']);
    }

    /**
     * The key is never treated as an arbitrary "render me anything" trigger — only the exact,
     * known, non-PHI filename shape GenerateMonthlyPdf itself produces is honoured for
     * regeneration. Anything else still 404s exactly as it did before this fix.
     */
    public function test_a_key_that_does_not_match_the_known_filename_shape_still_404s(): void
    {
        Storage::fake('local');
        $admin = $this->admin();

        foreach ([
            'not-a-real-key.pdf',
            '../../etc/passwd',
            'monthly-2024-abc.pdf',      // userId must be numeric
            'monthly-24-'.$admin->id.'.pdf', // year must be 4 digits
            'monthly-2024-'.$admin->id,      // missing .pdf
        ] as $badKey) {
            $this->actingAs($admin)->get('/reports/pdf-download/'.rawurlencode($badKey))
                ->assertNotFound();
        }
    }

    public function test_download_still_serves_the_existing_file_without_regenerating_when_present(): void
    {
        Storage::fake('local');
        $admin = $this->admin();
        $key = "monthly-2024-{$admin->id}.pdf";
        // a placeholder that is NOT a real booklet render — if the fix regenerated unconditionally
        // this would come back as a real multi-page PDF instead of this exact placeholder content
        Storage::disk('local')->put("reports/{$key}", '%PDF-1.4 already-generated-placeholder');

        $res = $this->actingAs($admin)->get("/reports/pdf-download/{$key}");

        $res->assertOk();
        // still exactly the placeholder that was already on disk — proves the existing-file path
        // was never routed through regeneration at all
        $this->assertSame('%PDF-1.4 already-generated-placeholder', Storage::disk('local')->get("reports/{$key}"));
    }
}
